version: '3.8'

services:
  app:
    image: izquiratops/tango:latest
    ports:
      - "8080:8080"
    networks:
      - happy-net
    volumes:
      - ./jmdict_source:/app/jmdict_source
    environment:
      - TANGO_VERSION=3.6.1
      - TANGO_REBUILD=true
    command: ["./app/tango"]

  mongo:
    image: mongo:latest
    networks:
      - happy-net
    volumes:
      - mongodb_data:/data/db

networks:
  happy-net:
    driver: bridge

volumes:
  mongodb_data: