version: '3.8'

services:
  app:
    image: izquiratops/tango:latest
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    networks:
      - happy-net
    volumes:
      - ${TANGO_JMDICT_SOURCE_PATH}:/app/jmdict_source
    environment:
      - TANGO_VERSION=${TANGO_VERSION}
      - TANGO_REBUILD=${TANGO_REBUILD}
    command: ["./app/tango"]

  mongo:
    image: mongo:latest
    networks:
      - happy-net
    volumes:
      - mongodb_data:/data/db

networks:
  happy-net:
    driver: bridge

volumes:
  mongodb_data: