version: '3.8'

services:
  app:
    image: izquiratops/tango:latest
    ports:
      - "8080:8080"
    environment:
      DB_VERSION: "3.6.1"
    volumes:
      - /custom/path/to/bleve:/root
    command: ["--rebuild-database=true"]

  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    secrets:
      - mongo-root-username
      - mongo-root-password

secrets:
  mongo-root-username:
    file: ./mongo-root-username.txt
  mongo-root-password:
    file: ./mongo-root-password.txt

volumes:
  mongodb_data: