services:
  client:
    image: izquiratops/tango:latest
    restart: unless-stopped
    networks:
      - tango-net
    volumes:
      - ./jmdict_source:/root/jmdict_source
      - ./static:/root/client/static
      - ./template:/root/client/template
    env_file:
      - .env

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - tango-net
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      - tango-net
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 86400 --cleanup

networks:
  tango-net:
    driver: bridge

volumes:
  mongodb_data:
  caddy_data:
  caddy_config: