version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ${TANGO_BLEVE_PATH}:/root
    command: ["./app/tango"]
    environment:
      - TANGO_VERSION=${TANGO_VERSION}
      - TANGO_REBUILD=${TANGO_REBUILD}
      - TANGO_BLEVE_PATH=${TANGO_BLEVE_PATH}

  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: