name: Transfer Static Files

on:
  push:
    branches:
      - main
    paths:
      - 'client/template/**'
      - 'client/static/**'
  workflow_dispatch:

env:
  DROPLET_HOST: "izquiratops.dev"

jobs:
  compress-and-transfer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Allow to read the commit history
      
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github_actions_deploy
          chmod 600 ~/.ssh/github_actions_deploy

          # Config SSH
          echo "Host ${{ env.DROPLET_HOST }}" > ~/.ssh/config
          echo "  ConnectTimeout 20" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  UserKnownHostsFile /dev/null" >> ~/.ssh/config
          echo "  IdentitiesOnly yes" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/github_actions_deploy" >> ~/.ssh/config
          chmod 600 ~/.ssh/config

          # Make sure everything works
          ssh ${{ secrets.DROPLET_USER }}@${{ env.DROPLET_HOST }} echo "SSH connection successful"
      
      - name: Compress all files
        run: |
          echo "Compressing all files..."
          find "client/static" -type f -not -name "*.gz" | while read file; do
            gzip -k "$file"
            echo "$file compressed."
          done

      - name: Transfer files
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" \
              client/template \
              "${{ secrets.DROPLET_USER }}@${{ env.DROPLET_HOST }}:template"
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" \
              client/static \
              "${{ secrets.DROPLET_USER }}@${{ env.DROPLET_HOST }}:static"

      - name: Cleanup
        run: |
          rm -f ~/.ssh/id_rsa
